CREATE TABLE "retail_sales_dataset" (
	"Transaction_ID"	INTEGER,
	"Date"	TEXT,
	"Customer_ID"	TEXT,
	"Gender"	TEXT,
	"Age"	INTEGER,
	"Product_Category"	TEXT,
	"Quantity"	INTEGER,
	"Price_per_Unit"	INTEGER,
	"Total Amount"	INTEGER
);



CREATE TABLE "weather" (
	"Longitude (x)"	REAL,
	"Latitude (y)"	REAL,
	"Station Name"	TEXT,
	"Climate ID"	INTEGER,
	"Date"	TEXT,
	"Year"	INTEGER,
	"Month"	INTEGER,
	"Day"	INTEGER,
	"Data Quality"	TEXT,
	"Max_Temp"	REAL,
	"Max Temp Flag"	TEXT,
	"Min_Temp"	REAL,
	"Min Temp Flag"	TEXT,
	"Mean_Temp"	REAL,
	"Mean Temp Flag"	TEXT,
	"Heat Deg Days (°C)"	REAL,
	"Heat Deg Days Flag"	TEXT,
	"Cool Deg Days (°C)"	REAL,
	"Cool Deg Days Flag"	TEXT,
	"Total_Rain"	TEXT,
	"Total Rain Flag"	TEXT,
	"Total_Snow"	TEXT,
	"Total Snow Flag"	TEXT,
	"Total_Precip_mm"	REAL,
	"Total Precip Flag"	TEXT,
	"Snow_on_Grnd_cm"	TEXT,
	"Snow_on_Grnd_Flag"	TEXT,
	"Dir of Max Gust (10s deg)"	TEXT,
	"Dir of Max Gust Flag"	TEXT,
	"Spd_of_Max_Gust_kmph"	TEXT,
	"Spd of Max Gust Flag"	TEXT
);

CREATE TABLE "weather_2024" (
	"Longitude (x)"	REAL,
	"Latitude (y)"	REAL,
	"Station Name"	TEXT,
	"Climate ID"	INTEGER,
	"Date"	TEXT,
	"Year"	INTEGER,
	"Month"	INTEGER,
	"Day"	INTEGER,
	"Data Quality"	TEXT,
	"Max_Temp"	REAL,
	"Max Temp Flag"	TEXT,
	"Min_Temp"	REAL,
	"Min Temp Flag"	TEXT,
	"Mean_Temp"	REAL,
	"Mean Temp Flag"	TEXT,
	"Heat Deg Days (°C)"	REAL,
	"Heat Deg Days Flag"	TEXT,
	"Cool Deg Days (°C)"	REAL,
	"Cool Deg Days Flag"	TEXT,
	"Total_Rain"	TEXT,
	"Total Rain Flag"	TEXT,
	"Total_Snow"	TEXT,
	"Total Snow Flag"	TEXT,
	"Total_Precip_mm"	REAL,
	"Total Precip Flag"	TEXT,
	"Snow_on_Grnd_cm"	TEXT,
	"Snow_on_Grnd_Flag"	TEXT,
	"Dir of Max Gust (10s deg)"	TEXT,
	"Dir of Max Gust Flag"	TEXT,
	"Spd_of_Max_Gust_kmph"	TEXT,
	"Spd of Max Gust Flag"	TEXT
);
